---
kind: pipeline
type: docker
name: default

steps:
- name: docker build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: jschlimmer/wcrp-web
    tags: 
      - latest
      - 0.1

trigger:
  branch: 
  - master
